# Site
repository: gustavkarlsson/gustavkarlsson.github.io
# favicon: images/favicon.ico

# Personal info
name: Gustav Karlsson
title: Software Engineer
email: gustav.karlsson@gmail.com
website: gustavkarlsson.github.io

# Social links
twitter_username: gkarlsson86
github_username:  gustavkarlsson
linkedin_username: gustavkarlsson86
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/profile.jpg 
about_content: |
  Hi, I'm Gustav. I'm a software engineer based in Frankfurt, Germany. I put 1's and 0's together to make stuff.

  I'm currently working as a Senior Android Developer for [ioki](https://ioki.com).

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: |
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Music (mostly jazz and funk)
   - Gaming
   - Philosophy
   - British panel shows
   - Long walks on the beach...

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
